### ISSUE TITLE
Can't load this theme with "load-theme" function

### ISSUE THREAD

**Issue by enzochiau** [fommil/darcula-theme-emacs#3]
After install this from package through elpy, when I try to run "load-theme" to load it, I got this error "Wrong type argument: stringp, nil"

I am using Emacs-24.4 on Linux

**Comment by theaqua** [comment]
Will it fix?

**Comment by fommil** [comment]
PRs welcome

**Comment by theaqua** [comment]
Are you serious? You can't fix code in 1 line?
I make PR, check #5.

**Comment by fommil** [comment]
@theaqua if I knew the fix, I wouldn't ask for a PR.

**Comment by theaqua** [comment]
https://github.com/fommil/darcula-theme-emacs/issues/3#issuecomment-66628893

**Comment by fommil** [comment]
Oh, you mean in the throwaway comment that somebody made when I was suffering from a high fever back in December? Oh, I'm terribly sorry for not immediately implementing it, your highness.

**Comment by dgutov** [comment]
@fommil That certain somebody was asked for help with your theme, and was thus forced to overcome this issue, even though he's unlikely to ever use this or any other dark-background theme.

A comment is plenty in this case, I believe.

**Comment by fommil** [comment]
@dgutov I was ill when you posted your comment, so I didn't understand that you'd fixed it.
