### ISSUE TITLE
don't hard-code font family

### ISSUE THREAD

**Issue by fommil** [fommil/darcula-theme-emacs#4]
several people have commented that they don't like fonts being defined in the theme.

**Comment by Naomarik** [comment]
Yes please, new vim user trying to switch to emacs via spacemacs. Would love to use this theme but have to find a workaround for the font family.

**Comment by fommil** [comment]
if you can work out how I can set the font family as a user-customisation option (and send me a PR), I'd happily merge this and it'll appear in MELPA within minutes. The problem I have is that I don't know how to set the font family for the various faces in my own config, without setting it in the theme.

**Comment by fommil** [comment]
that means for: `default`, `variable-pitch` and `fixed-pitch`.

**Comment by fommil** [comment]
ok, so I just don't mention Inconsolata. If you'd said it was **that** easy I would have done it already! :wink:

**Comment by Naomarik** [comment]
Nice - I didn't know it was that easy since emacs is still new to me. Still slowly trying to migrate from vim to emacs while loaded with work :)
