### ISSUE TITLE
Wrong background color

### ISSUE THREAD

**Issue by algui91** [fommil/darcula-theme-emacs#9]
Hi, Thanks for doing this theme!. I have one problem, the background color does not change, it is still white, I am using this:

```
(use-package darcula-theme
  :ensure t
  :config
  ;; your preferred main font face here
  (set-frame-font "Source Code Pro:pixelsize=13:foundry=adobe:weight=light:slant=normal:width=normal:spacing=100:scalable=true"))
```

**Comment by fommil** [comment]
something else must be interfering. BTW, this has moved to gitlab... I should delete / redirect this repo.
